# Generated by Django 5.0.1 on 2024-01-23 12:47

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Content Categories',
                'verbose_name_plural': 'Content Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('overview', models.CharField(db_index=True, max_length=250)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_published', models.BooleanField(default=False)),
                ('Location', models.CharField(blank=True, db_index=True, default='Kenya', max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Images/contentImages/')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('next_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='content.content')),
                ('previous_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='content.content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.contentcategories')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.content')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='PostFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('file', models.ImageField(upload_to='ckfiles/%Y/%m/%d/')),
                ('file_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
