# Generated by Django 5.0.1 on 2024-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tags_content_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='content',
        ),
        migrations.AddField(
            model_name='comments',
            name='content_comment',
            field=models.TextField(default='hey', max_length=80),
            preserve_default=False,
        ),
    ]
