# Generated by Django 5.0.1 on 2024-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_comments_content_comments_content_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail_caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
